compile :
	gcc -Wall -Wextra -Werror -D BUFFER_SIZE=42 get_next_line.c get_next_line_utils.c main.c
	./a.out

update :
	git add get_next_line.h
	git add get_next_line_utils.c
	git add get_next_line.c
	git commit -m "autocommit"
	git push
